name: sse
version: 4.0.0-nullsafety
homepage: https://github.com/dart-lang/sse
description: >-
  Provides client and server functionality for setting up bi-directional
  communication through Server Sent Events (SSE) and corresponding POST
  requests.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  logging: ^1.0.1
  pedantic: ^1.11.0
  stream_channel: ^2.1.0
  shelf: ^1.1.0

dev_dependencies:
  shelf_static: ^1.0.0
  test: ^1.17.0
  webdriver: ^3.0.0
